### ISSUE TITLE
[PETITION] Make a new console command

### ISSUE THREAD

**Issue by SiTWulf** [Archomeda/AutoSaliens#5]
Hi... We need more info.

Please make a "info" console command with this info:
Active Planet
Active Zone
Current Level (Exp/Next lvl)
Show total time in each planet.

**Comment by Archomeda** [comment]
> Active Planet

Command `joinedplanet` does exactly that.

> Active Zone

Command `joinedzone` does exactly that.

> Current Level (Exp/Next lvl)

Command `playerinfo` does exactly that.

> Show total time in each planet.

That's impossible. The API only supplies that information of the current planet you're on. I can't get that information from planets that no longer exist. And querying for this info, requires your account to move planets, which is something you'd rather not want it to do.

----

Now, regarding the first 3 commands, they only work in the automation mode, not in Discord Presence only. It's something I intent to change, but I want to refactor a bunch of stuff first before I do that.

**Comment by SiTWulf** [comment]
`playerinfo` not appear in Help command or Readme in this page.

**Comment by Archomeda** [comment]
Whoops, that's my bad. I must've overlooked it. It most definitely exists though ;)

**Comment by tonyrayo** [comment]
Cheers for the constant improvements (OT but needs to be said)!
